tasks:
  - init: |
      curl -O https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-cli-linux-x86_64.tar.gz
      tar -xf google-cloud-cli-linux-x86_64.tar.gz
      mkdir -p /workspace/tools
      mv google-cloud-sdk/ /workspace/tools/google-cloud-sdk
      /workspace/tools/google-cloud-sdk/install.sh --quiet
      echo 'PATH=/workspace/tools/google-cloud-sdk/bin:$PATH' >> ~/.bashrc
      rm google-cloud-cli-*
      . ~/.bashrc
